# Generated by Django 4.2.3 on 2023-08-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('s_number', models.TextField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regNo', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0, max_length=12)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.books')),
            ],
        ),
    ]
