# Generated by Django 4.2.3 on 2023-08-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regNo', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.AddField(
            model_name='member',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
    ]
