# Generated by Django 4.2.3 on 2023-08-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_book_status_alter_book_s_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='books',
        ),
    ]
