# Generated by Django 4.2.3 on 2023-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_book_borrow_date_book_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.IntegerField(default=''),
        ),
    ]
